# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-01 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadWriteDelete', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
